import Head from "next/head";
import Image from "next/image";
import { kAppName } from "../util/constants";
import { FiSearch } from "react-icons/fi";
import { useState } from "react";

export async function getStaticProps(context) {
  var result = await fetch("http://localhost:8080/api/v1/users");
  var users = await result.json();

  return {
    props: {
      users,
    },
  };
}

// https://images.unsplash.com/photo-1577044685231-70e99274404c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80
// {users.map((person) => (
// <div key={person.id} className="flex">
// <p className="">
// {person.first_name} {person.last_name}
// </p>
// </div>
// ))}

export default function Home({ users }) {
  const [currentUser, setCurrentUser] = useState(users[5]);

  return (
    <div className="w-screen min-h-screen bg-gray-50">
      <Head>
        <title>{kAppName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row h-full w-full">
        {/* sidebar */}
        <aside className="min-h-screen sticky inset-y-0 h-full w-56 bg-white shadow-sm z-50"></aside>

        {/* main content */}
        <div className="flex-1">
          {/* fixed header */}
          <header className="h-24 inset-x-0 sticky top-0 bg-white shadow-sm z-50">
            <div className="flex flex-row justify-between items-center py-6 h-full w-full max-w-6xl mx-auto">
              {/* left */}
              <div className="flex space-x-4 items-center">
                <h6 className="font-medium text-sm cursor-pointer text-gray-600 transition-colors duration-150 hover:text-blue-400">
                  About
                </h6>
                <h6 className="font-medium text-sm cursor-pointer text-gray-600 transition-colors duration-150 hover:text-blue-400">
                  Help
                </h6>
              </div>

              {/* center */}
              <div
                onClick={() => alert("search not working")}
                className="cursor-pointer flex flex-row w-1/3 bg-gray-100 h-full rounded-full px-8 items-center text-gray-500 space-x-4"
              >
                <FiSearch />
                <h6 className="text-sm">Search anything...</h6>
              </div>

              {/* right */}
              <div className="flex space-x-4 items-center">
                {currentUser && (
                  <>
                    {/* user avatar */}
                    <div className="rounded-full h-10 w-10 overflow-hidden">
                      <Image
                        src={currentUser.avatar}
                        height={40}
                        width={40}
                        objectFit="cover"
                      />
                    </div>

                    {/* username */}
                    <p className="font-medium text-sm">
                      {currentUser.first_name} {currentUser.last_name}
                    </p>
                  </>
                )}
              </div>
            </div>
          </header>

          {/* scrolling content */}
          <main className="absolute left-56 right-0 top-24 bottom-0">
            <div className="relative h-full w-full">
              {/* banner image */}
              <div className="overflow-hidden h-1/4 w-full rounded-br-3xl absolute top-0 inset-x-0">
                <img
                  src={
                    "https://images.unsplash.com/photo-1577044685231-70e99274404c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80"
                  }
                  className="object-cover w-full h-full"
                />
              </div>

              {/* content */}
              <div className="grid grid-cols-10 gap-x-4 h-full pt-40 mx-auto w-full max-w-6xl">
                {/* profile */}
                <div className="flex col-span-3 w-full h-3/4 bg-white rounded-xl sticky top-0"></div>

                {/* tweets */}
                <div className="flex col-span-4 w-full h-full bg-white rounded-xl sticky top-0"></div>

                {/* trends */}
                <div className="flex col-span-3 w-full h-3/4 bg-white rounded-xl sticky top-0"></div>
              </div>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}
